### ISSUE TITLE
Collisions with Riak Core because of shared modules

### ISSUE THREAD

**Issue by cmeiklejohn** [helium/plumtree#16]
Shared modules, such as ```dvvset```, ```app_helper```, ```hashtree```, and ```hashtree_tree``` prevent an application from including both Riak Core and Helium's Plumtree.  

To get around this in Lasp, we've extracted the common code out into a library called ```lasp_support```, but a proper fix would be great.  We're maintaining a fork of ```plumtree``` and ```riak_core``` in the mean time.

https://github.com/lasp-lang

**Comment by tsantero** [comment]
resolved by https://github.com/helium/plumtree/pull/26 and https://github.com/helium/plumtree/pull/29
