### ISSUE TITLE
Metadata manger race conditions lead to crash of peer service

### ISSUE THREAD

**Issue by cmeiklejohn** [helium/plumtree#19]
Access to the metadata state for the peer service is not managed via a serial actor; even with a CRDT, serial access to the replica is _required_ to prohibit data loss from concurrency anomalies. (see #18)

Additionally, given serial access is not used via a ```gen_server```, race conditions can occur if node clustering occurs during the initialization phase, given state has not been fully persisted yet.

See excerpt of crash, due to join during initialization over state not managed by a ```gen_server```:

```
12:00:20.885 [info] Deployed nodes: ['dev1@127.0.0.1','dev2@127.0.0.1','dev3@127.0.0.1']
12:00:20.913 [info] [join] 'dev2@127.0.0.1' to ('dev1@127.0.0.1'): {badrpc,{'EXIT',{badarg,[{erlang,hd,[[]],[]},{plumtree_peer_service_manager,get_local_state,0,[{file,"src/plumtree_peer_service_manager.erl"},{line,43}]},{plumtree_peer_service,attempt_join,1,[{file,"src/plumtree_peer_service.erl"},{line,56}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,205}]}]}}}
12:00:20.914 [error] Error in process <0.106.0> on node 'riak_test@127.0.0.1' with exit value: {{assertEqual_failed,[{module,lasp_test_helpers},{line,131},{expression,"R"},{expected,ok},{value,{badrpc,{'EXIT',{badarg,[{erlang,hd,[[]],[]},{plumtree_peer_service_manager,get_local_state,0,[{file,"src/plumtree_peer_... 
```

**Comment by cmeiklejohn** [comment]
I've got a patched version of this in the Lasp fork of Plumtree.

**Comment by cmeiklejohn** [comment]
Addressed by https://github.com/helium/plumtree/pull/23.

**Comment by tsantero** [comment]
satisfied by https://github.com/helium/plumtree/pull/26
