### ISSUE TITLE
Bogus tag for eleveldb in rebar.lock

### ISSUE THREAD

**Issue by slfritchie** [helium/plumtree#24]
Howdy.  On the 'master' branch at commit 61d8925c703249620536fbf9df90015a03b11f09, there is a bogus tag for eleveldb in the file `rebar.lock`.

    % cd plumtree
    % make
    ./rebar3 compile
    ===> Verifying dependencies...
    ===> Fetching eleveldb ({git,"git://github.com/helium/eleveldb.git",
                                       {ref,
                                           "29a5360dc0365b3330dd0cd45b0b8166f3b854be"}})
    ===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
    ===> When submitting a bug report, please include the output of `rebar3 wtf "your command"`
    make: *** [compile] Error 1

If I remove the entry for leveldb from `rebar.lock`, then I have no problem.   .... Hrrrm, is `rebar.lock` even supposed to be checked in? If I run `rm rebar.lock ; make test`, then I get some odd complaints from rebar3, but then the compilation & testing goes on.

    ESC[0;32m===> Verifying dependencies...
    ESC[0mESC[0;32m===> Fetching eleveldb ({git,"git://github.com/helium/eleveldb.git",
                                        {branch,"adt-helium"}})
    ESC[0mESC[0;35m===> Skipping eleveldb (from {git,
                                         "git://github.com/helium/eleveldb.git",
                                         {branch,"adt-helium"}}) as an app of the same name has already been fetched
    
    ESC[0mESC[0;32m===> Fetching lager ({git,"git://github.com/basho/lager.git",
                                     {tag,"2.1.1"}})
    ESC[0mESC[0;35m===> Skipping lager (from {git,"git://github.com/basho/lager.git",
                                          {tag,"2.1.1"}}) as an app of the same name has already been fetched
    
    ESC[0mESC[0;32m===> Fetching riak_dt ({git,"git://github.com/basho/riak_dt.git",
                                       {tag,"2.1.0"}})
    ESC[0mESC[0;35m===> Skipping riak_dt (from {git,"git://github.com/basho/riak_dt.git",
                                           {tag,"2.1.0"}}) as an app of the same name has already been fetched
    
    ESC[0mESC[0;32m===> Fetching goldrush ({git,"git://github.com/DeadZen/goldrush.git",
                                        {tag,"0.1.6"}})
    ESC[0mESC[0;35m===> Skipping lager (from {git,"git://github.com/basho/lager.git",
                                          {tag,"2.1.1"}}) as an app of the same name has already been fetched
    
    ESC[0mESC[0;32m===> Compiling goldrush

**Comment by cmeiklejohn** [comment]
My recommendation is for Helium to pull in the changes from the Lasp fork of plumtree, given it's got several improvements.

**Comment by cmeiklejohn** [comment]
Resolved by #26.

**Comment by Vagabond** [comment]
I don't actually think this is a bogus tag, it is rebar not switching git origins:

https://github.com/helium/eleveldb/tree/adt-helium

This is something we needed so things would work with rebar3, maybe no longer necessary?

**Comment by cmeiklejohn** [comment]
So, is this a bug that should be filed on rebar3?

**Comment by Vagabond** [comment]
No, it is because rebar3 (at least at the time this was done) didn't want to be in the business of compiling C, so the recommendation was to use Make to do it, which is what this branch of eleveldb does.

**Comment by cmeiklejohn** [comment]
No, I understand that.  I meant the error where it can't pull the ref.

**Comment by Vagabond** [comment]
Yeah, rebar doesn't compare origins, just the name of the dep and the branch/tag/ref. I don't know if it is something the rebar folks are interested in fixing though, it has been around a looooong time.

**Comment by tsloughter** [comment]
We do compare the origin. At least we have for a while. May be update the copy of rebar3? We are close to releasing a stable 3.0, but I'd suggest updating to beta-3 or master now anyway.
