### ISSUE TITLE
how peers crash handled?

### ISSUE THREAD

**Issue by benoitc** [helium/plumtree#36]
i was looking in the code for it but i don't see right now what happen if a peer node crash? how do we know that this peer disappeared?

**Comment by cmeiklejohn** [comment]
Can you define what you mean by the term crash?  Do you mean a node that crashes but returns with it's storage or a node that returns as a new member of a cluster?

**Comment by benoitc** [comment]
hrm  I was thinking to " a node that crashes but returns with it's storage"

**Comment by cmeiklejohn** [comment]
If a node crashed and returned with stable storage -- does this appear to the system any different from a network partition?

**Comment by benoitc** [comment]
hrm I don't think so... somehow got my answer :)
